language: cpp

matrix:
 include:
  - os: linux
    dist: trusty
    compiler: gcc
    env:
     - QT_BASE=54
  - os: linux
    dist: trusty
    compiler: gcc
    env:
     - QT_BASE=55
  - os: linux
    dist: trusty
    compiler: gcc
    env:
     - QT_BASE=56
  - os: linux
    dist: trusty
    compiler: gcc
    env:
     - QT_BASE=57
  - os: linux
    dist: trusty
    compiler: gcc
    env:
     - QT_BASE=58
  - os: linux
    dist: trusty
    compiler: gcc
    env:
     - QT_BASE=59
  - os: linux
    dist: trusty
    compiler: gcc
    env:
     - QT_BASE=510
  - os: linux
    dist: trusty
    compiler: gcc
    env:
     - QT_BASE=511
  - os: osx
    compiler: clang
    env:
     - QT_BASE=latest

before_install:
  - if [ "$QT_BASE" = "52" ]; then sudo add-apt-repository ppa:beineri/opt-qt521-trusty -y; fi
  - if [ "$QT_BASE" = "53" ]; then sudo add-apt-repository ppa:beineri/opt-qt532-trusty -y; fi
  - if [ "$QT_BASE" = "54" ]; then sudo add-apt-repository ppa:beineri/opt-qt542-trusty -y; fi
  - if [ "$QT_BASE" = "55" ]; then sudo add-apt-repository ppa:beineri/opt-qt551-trusty -y; fi
  - if [ "$QT_BASE" = "56" ]; then sudo add-apt-repository ppa:beineri/opt-qt562-trusty -y; fi
  - if [ "$QT_BASE" = "57" ]; then sudo add-apt-repository ppa:beineri/opt-qt571-trusty -y; fi
  - if [ "$QT_BASE" = "58" ]; then sudo add-apt-repository ppa:beineri/opt-qt58-trusty -y; fi
  - if [ "$QT_BASE" = "59" ]; then sudo add-apt-repository ppa:beineri/opt-qt594-trusty -y; fi
  - if [ "$QT_BASE" = "510" ]; then sudo add-apt-repository ppa:beineri/opt-qt-5.10.1-trusty -y; fi
  - if [ "$QT_BASE" = "511" ]; then sudo add-apt-repository ppa:forkotov02/opt-qt-5.11.1-trusty -y; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then
      sudo apt-get update -qq;
    else
      brew update;
    fi

install:
  - if [ "$QT_BASE" = "54" ]; then sudo apt-get install -qq qt54base; source /opt/qt54/bin/qt54-env.sh; fi
  - if [ "$QT_BASE" = "55" ]; then sudo apt-get install -qq qt55base; source /opt/qt55/bin/qt55-env.sh; fi
  - if [ "$QT_BASE" = "56" ]; then sudo apt-get install -qq qt56base; source /opt/qt56/bin/qt56-env.sh; fi
  - if [ "$QT_BASE" = "57" ]; then sudo apt-get install -qq qt57base; source /opt/qt57/bin/qt57-env.sh; fi
  - if [ "$QT_BASE" = "58" ]; then sudo apt-get install -qq qt58base; source /opt/qt58/bin/qt58-env.sh; fi
  - if [ "$QT_BASE" = "59" ]; then sudo apt-get install -qq qt59base; source /opt/qt59/bin/qt59-env.sh; fi
  - if [ "$QT_BASE" = "510" ]; then sudo apt-get install -qq qt510base; source /opt/qt510/bin/qt510-env.sh; fi
  - if [ "$QT_BASE" = "511" ]; then sudo apt-get install -qq qt511base; source /opt/qt511/bin/qt511-env.sh; fi
  - if [ "$QT_BASE" = "latest" ]; then
      brew install qt5;
      brew link --force qt5;
    fi

script:
  - qmake -v
  - mkdir build && cd build
  - qmake -r ../
  - make

notifications:
  email: false
